mj:
  accounts:
    - guild-id: 1193774915313209344
      channel-id: 1194215921976344646
      user-token: MTEyNTMzMTMyNTEyNjIwMTQxNQ.Gvwyjp.fqhrsLil6QZwJr6eKp1fMCLnlKbxSxsKShorlY
#    - guild-id: xxx
#      channel-id: xxx
#      user-token: xxxx
#      user-agent: xxxx
  